---
# tasks file for install_kibana
- name: Install kibana for Ubuntu
  apt:
    name: kibana
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install kibana for CentOS
  yum:
    name: kibana
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"
